export const USER_TYPES = {
  VISITOR: 'VISITOR',
  POLLEE: 'POLLEE',
  POLLER: 'POLLER'
};

export const POLLEE_STATUSES = {
  VOTE_CAST: 'VOTE_CAST',
  DECIDING_VOTE: 'DECIDING_VOTE',
  FINISHED_POLLING: 'FINISHED_POLLING'
};

export const POLL_TYPES = {
  RANGE: 'RANGE'
};
